RPWR/urls.py
from django.conf.urls import *
from django.contrib import admin
from information.views import *

information_resource = InformationResource()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
	url(r'^$', home, name='home'),
	url(r'^add_student/$', add_student, name='add_student'),
	url(r'^details/(?P<form_id>\d+)/$', details, name='details'),
	url(r'^edit/(?P<form_id>\d+)/$', edit_student, name='edit_student'),
    url(r'^api/', include(information_resource.urls)),
    url(r'^welcome/$', welcome, name='welcome'),
    url(r'^error/$', error, name='error'),
]

urlpatterns += [
    url(r'^accounts/login/$', 'cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'cas.views.logout', name='logout'),
]

information/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
		
class Building(models.Model):
	def __unicode__(self):
		return self.Building_Name
	Building_Name = models.CharField(max_length = 8)

class BuildingImage(models.Model):
	building = models.ForeignKey(Building)
	def __unicode__(self):
		return ''
	image = models.ImageField()

class Information(models.Model):
	Index = models.IntegerField(blank = True, null = True)
	Building_option = models.ManyToManyField(Building)
	# Building_option = models.CharField(max_length = 6)
	Room = models.IntegerField()
	Desk = models.CharField(max_length = 6)
	Extension = models.IntegerField(blank = True, null = True)
	UWID = models.IntegerField()
	Email = models.EmailField(blank = True, null = True)
	Last_Name = models.CharField(max_length = 15)
	First_Name = models.CharField(max_length = 15)
	Status = models.CharField(max_length = 6)
	First_Supervisor = models.CharField(max_length = 20)
	Second_Supervisor = models.CharField(blank = True, max_length = 20)
	Third_Supervisor = models.CharField(blank = True, max_length = 20)
	Start_Date = models.DateField()
	End_Date = models.DateField()
	FOB = models.BooleanField(default = False)
	FOB_pu = models.BooleanField(default = False)
	Added_to_existing_FOB = models.BooleanField(default = False)
	def __unicode__(self):
		return self.First_Name+' '+self.Last_Name

information/forms.py
from django.forms import *
from information.models import *
from django.contrib.admin import widgets 



class InformationForm(ModelForm):
	class Meta:
		model = Information
		fields = ['Index', 'Building_option', 'Room', 'Desk', 'Extension', 'UWID', 'Email', 'Last_Name', 'First_Name', 'Status', 'First_Supervisor', 'Second_Supervisor', 'Third_Supervisor', 'Start_Date', 'End_Date', 'FOB', 'FOB_pu', 'Added_to_existing_FOB']
		Building_option = MultipleChoiceField(
			choices = Building,
			required = True
			)
	def __init__(self, *args, **kwargs):
		super(InformationForm, self).__init__(*args, **kwargs)
		for field_name, field in self.fields.items():
			field.widget.attrs['class'] = 'form-control'
		# self.fields['Building_option'].choice = Building.objects.all().values_list('Building_Name', 'Building_Name')
		self.fields['Start_Date'].widget.attrs['class'] = 'form-control datepicker'
		self.fields['End_Date'].widget.attrs['class'] = 'form-control datepicker'
		# self.fields['Building_option'].widget.attrs['class'] = 'form-control'
		# self.fields['Building_option'].widget.attrs.pop('multiple', False) 
		# self.fields['Building_option'].widget.attrs['multiple']

# class BuildingForm(ModelForm):
# 	class Meta:
# 		model = Building
# 		fields = ['Building_Name']

	# buildingnames = ModelMultipleChoiceField(queryset = Information.objects.all())

# 	def __init__(self, *args, **kwargs):
# 		super(BuildingForm, self).__init__(*args, **kwargs)
# 		self.fields['Building_Name'].choice = Information.objects.all().values_list('Building_Name', 'Building_Name')

information/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from information.models import *
from information.forms import *
from django.forms.models import inlineformset_factory
import json
from django.contrib.auth.decorators import login_required, user_passes_test
# from django.utils import simplejson
def is_member(user):
	if user.is_authenticated:
		return user.groups.filter(name='Administrators').exists()

# @user_passes_test(is_member, '/error/',redirect_field_name = '')
def welcome(request):
	if request.user.is_authenticated() and is_member(request.user):
		return HttpResponseRedirect('/')
	elif request.user.is_authenticated() and not is_member(request.user):
		return HttpResponseRedirect('/error/')
	else:
		return render(request, 'welcome.html')

def error(request):
	if is_member(request.user):
		return HttpResponseRedirect('/welcome/')
	else:
		return render(request, 'error.html')


# @user_passes_test(is_member, '/error/',redirect_field_name = '')
@user_passes_test(is_member, '/welcome/',redirect_field_name = '')
def home(request):
	form = Information.objects.all()
	# buildinglist = []
	# for i in form:
	# 	x=i.Building.upper()
	# 	# buildinglist = [x.upper() for x in buildinglist]
	# 	if x not in buildinglist:
	# 		buildinglist.append(x)
	# building_list = json.dumps(buildinglist)
	# print building_list
	building = Building.objects.all()
	return render(request, 'home.html', {'form': form, 'building': building})

@user_passes_test(is_member, '/error/',redirect_field_name = '')
def add_student(request):
	# BuildingFormSet = inlineformset_factory(Information, Building,form = BuildingForm, extra = 1, can_delete = True)
	if request.method == 'POST':
		form = InformationForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			i = form.save(commit = False)
			i.save()
			print i.Building_option, 'asdfafsasdfasfhkafskj h'
			# form.save_m2m()
			# print i.id, "ID let us see what this is after save"
			return HttpResponseRedirect('/details/'+str(i.id))
	else:
		i = Information()
		# build = BuildingFormSet(instance = i)
		form = InformationForm(instance = i)
		# print form.Start_Date
	return render(request, 'edit.html', {'form': form})


	# return HttpResponseRedirect('/edit/%s' % i.id)
@user_passes_test(is_member, '/error/',redirect_field_name = '')
def edit_student(request, form_id):
	i = get_object_or_404(Information, pk=form_id)
	# i = Information.objects.get(pk = form_id)
	print request.method, 'asdfasfae fde asd'
	# form = 1
	if request.method == "POST":
		form = InformationForm(request.POST, instance = i)
		if form.is_valid():
			cd = form.cleaned_data
			i.save()
			return HttpResponseRedirect('/details/'+form_id)
	else:
		form = InformationForm(instance = i)
	return render(request, 'edit.html', {'form': form, 'info': i})

@user_passes_test(is_member, '/error/',redirect_field_name = '')
def details(request, form_id):
	form = get_object_or_404(Information, pk=form_id)
	return render(request, 'details.html', {'form': form})

from tastypie.resources import ModelResource, Resource
from tastypie.paginator import Paginator
from tastypie.authorization import Authorization, ReadOnlyAuthorization
from tastypie.exceptions import Unauthorized
from tastypie.authentication import SessionAuthentication, ApiKeyAuthentication, MultiAuthentication, BasicAuthentication
from tastypie.cache import NoCache, SimpleCache
from tastypie.constants import ALL, ALL_WITH_RELATIONS
from tastypie.fields import CharField
from tastypie import fields

class UserPickAuthorization(Authorization):
	def authorize_user(self, bundle):
		print 'Authorize User'

class InformationResource(ModelResource):
	class Meta:
		queryset = Information.objects.all()
		resource_name = "Information"
		allowed_methods = ['get']
		authorization = UserPickAuthorization()
		authentication = MultiAuthentication(SessionAuthentication(), ApiKeyAuthentication())
		filtering = {'Building':ALL}
		cache = NoCache()

def obj_create(self, bundle, request = None, **kwargs):
	return super(DatabaseResource, self).obj_create(bundle, request, user=request.user)

templates/details.html
{% extends 'skin.html' %}
{% block top-header %}
{% include 'sidebar.html' %}
<li class="page-scroll">
	<a href="/edit/{{form.id}}" title = 'Edit this form'>
		<i class="fa fa-edit fa-fw"></i>
		Edit this form
	</a>
</li>
{% endblock %}
{% block content %}

<div id = 'thetable' style = "" class = 'col-md-8 col-md-offset-2'>
	<table id = "test2" class = "table  table-boarder table-hover table-striped" style = 'background-color:white;'>
		<tr>
			<th colspan = "2">
				<center>
					<h3>
						Research Personal Workspace Registry
					</h3>
				</center>
			</th>
		</tr>
	
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%' >
					Index
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Index}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Building
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Building_option}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Room
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Room}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Desk
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Desk}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Extention
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Extention}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Student ID
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.UWID}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Email
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Email}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Last Name
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Last_Name}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					First Name
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.First_Name}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Status
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Status}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					First Supervisor
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.First_Supervisor}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Second Supervisor
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Second_Supervisor}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Third Supervisor
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Third_Supervisor}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Start Date
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Start_Date}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					End Date
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.End_Date}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					FOB
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.FOB}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					FOB p/u
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.FOB_pu}}
				</center>
			</td>
		</tr>
		<tr>
			<th>
				<center style = 'text-align:left; margin-left: 50%'>
					Added to existing FOB
				</center>
			</th>
			<td>
				<center style = 'text-align:left; margin-left: 30%'>
					{{form.Added_to_existing_FOB}}
				</center>
			</td>
		</tr>
{% endblock %}

{% block script %}
	<script type="text/javascript">
		$('.datepicker').datepicker({
			// format: "mm-yyyy",
			// viewMode: "months", 
			// minViewMode: "months"
		})
	</script>
{% endblock %}

templates/edit.html
{% extends 'skin.html' %}
{% block content %}
<div id='form_title' class = 'col-lg-8 col-lg-offset-2' >
	<table id = "test2" class = "table ">
		<th  colspan = "2">
			<center>
				<h3>
					Research Personal Workspace Registry
				</h3>
			</center>
		</th>
	</table>

	<form id = 'mainform' action="" method="post">
	{% csrf_token %}
		<table id='form_contant' class = "table table-boarder table-hover table-striped">
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Index
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Index}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Building
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Building_option}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Room
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Room}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Desk
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Desk}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Extension
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Extension}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Student ID
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.UWID}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Email
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Email}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Last Name
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Last_Name}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						First Name
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.First_Name}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Status
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Status}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						First Supervisor
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.First_Supervisor}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Second Supervisor
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Second_Supervisor}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Third Supervisor
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Third_Supervisor}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Start Date
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Start_Date}}
						</strong>
					</center>
				</td>
			</tr>

			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						End Date
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.End_Date}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						FOB
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.FOB}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						FOB p/u
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.FOB_pu}}
						</strong>
					</center>
				</td>
			</tr>
			<tr>
				<th>
					<center style = 'text-align:left; margin-left: 50%'>
						Added to existing FOB
					</center>
				</th>

				<td>
					<center style = 'text-align:left; margin-left: 0%; width: 65%;'>
						<strong>
							{{form.Added_to_existing_FOB}}
						</strong>
					</center>
				</td>
			</tr>
		</table>

		<table id="savebutton_table" class="table">
			<tr>
				<th>
					<center>
							<input id = 'save_button' class = "btn btn-default" data-toggle="modal" type="submit" value = "Save">
							<a href = '/' class = "btn btn-default">
								Cancel
							</a>
					</center>
				</th>
			</tr>
		</table>
	</form>
</div>
{% endblock %}

{% block script %}
	<script type="text/javascript">
		$(document).ready(function(){
			$('#id_Start_Date').datepicker({
				format: 'mm/dd/yyyy',
			})
			$('#id_End_Date').datepicker({
				format: 'mm/yyyy',
			})
			$('#id_Building_option').removeAttr('multiple');
			$('#id_Building_option').append('<option value="" disabled selected>Select a building</option>')
			$('#id_Building_option').on('change', function(){
				console.log($(this).val())
			})
		});
	</script>
{% endblock %}

templates/error.html
{% extends 'skin.html' %}
{% block style %}
	<style>
		thead input {
			width: 100%;
			height: 100%;
			box-sizing: border-box;
		}
		#page-wrapper {
			-webkit-box-shadow: inset 0px 0px 19px 0px rgba(0,0,0,0.4);
			-moz-box-shadow: inset 0px 0px 19px 0px rgba(0,0,0,0.4);
			box-shadow: inset 0px 0px 19px 0px rgba(0,0,0,0.4);
		}
		#thetable {
			-webkit-box-shadow: 0px 0px 19px 0px rgba(0,0,0,0.3);
			-moz-box-shadow: 0px 0px 19px 0px rgba(0,0,0,0.3);
			box-shadow: 0px 0px 19px 0px rgba(0,0,0,0.3);
		}
		#add_tool {
			-webkit-box-shadow: 0px 0px 19px 0px rgba(0,0,0,0.3);
			-moz-box-shadow: 0px 0px 19px 0px rgba(0,0,0,0.3);
			box-shadow: 0px 0px 19px 0px rgba(0,0,0,0.3);
		}
	</style>
{% endblock %}
{% block content %}
	<div id="wrapper" >
		<!-- Navigation -->
<!-- 		<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
		<div class="navbar-header">
		<a href="http://uwaterloo.ca/science/">
		<img src="/static/sciencelogo.png" alt="Link to the University of Waterloo Science home page" width="213" height="51" vspace="15" hspace="15" />
		</a>
		</div>				
		</nav> -->

		<h3>
			<center>
				403 - ACCESS DENIED
			</center>
		</h3>
		<p> </p>

		{% if user.is_authenticated %}
			<center>
				<p style = 'margin-left: 5%;'>
				You are not authorized to access this page.
				</p>
				<p style = 'margin-left: 5%;'>
				Please
				<a href ='/accounts/logout/'>
				Log out
				</a>
				and contact the administrators for access if eligible.
				</p>
			</center>	        
		{% else %}
			<center>
				<p style = 'margin-left: 5%;'>
				You are not logged in to access this page.
				</p>
				<p style = 'margin-left: 5%;'>
				Please
				<a href ='/'>
				Log In
				</a>
				and check back in. That’s all we know.
				</p>
			</center>
		{% endif %}
	</div>
{% endblock %}

templates/sidebar.html
<li class="page-scroll">
	<a href="/add_student/" title = 'Add a new certificate'>
		<i class="fa fa-plus fa-fw"></i>
		Add Student
	</a>
</li>

templates/welcome.html
{% extends 'skin.html' %}
{% block style %}
	<style type="text/css">
		.wrapper {    
			margin-top: 80px;
			margin-bottom: 20px;
		}

		.form-signin {
		  max-width: 420px;
		  padding: 30px 38px 66px;
		  margin: 0 auto;
		  background-color: #eee;
		  border: 3px dotted rgba(0,0,0,0.1);  
		  }

		.form-signin-heading {
		  text-align:center;
		  margin-bottom: 30px;
		}

		.form-control {
		  position: relative;
		  font-size: 16px;
		  height: auto;
		  padding: 10px;
		}

		input[type="text"] {
		  margin-bottom: 0px;
		  border-bottom-left-radius: 0;
		  border-bottom-right-radius: 0;
		}

		input[type="password"] {
		  margin-bottom: 20px;
		  border-top-left-radius: 0;
		  border-top-right-radius: 0;
		}

		.colorgraph {
		  height: 7px;
		  border-top: 0;
		  background: #c4e17f;
		  border-radius: 5px;
		  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
		  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
		  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
		  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
		}
	</style>
{% endblock %}

{% block content %}
<div class = "container">
	<div class="wrapper">     
		<h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
		<hr class="colorgraph"><br>


		<a class="btn btn-lg btn-primary btn-block" href="/accounts/login">Login</a>  					
	</div>
</div>
{% endblock %}